version: "3.9"
services:
  zookeeper-server:
    image: 'zookeeper:latest'
    ports:
      - '2181:2181'
    networks:
      - my-app-network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
    networks:
      - my-app-network
networks:
  my-app-network:
    driver: bridge
volumes:
  mymongodb_container:

